// <auto-generated />
using System;
using System.Collections.Generic;
using DietAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietAI.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621134624_AddKeycloakUsers")]
    partial class AddKeycloakUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietAI.Api.Services.AiPlanSender.Models.Diets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Allergies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("CaloricValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DietType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ExcludedIngredients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("ForHeight")
                        .HasColumnType("numeric");

                    b.Property<int>("ForSex")
                        .HasColumnType("integer");

                    b.Property<decimal>("ForWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Diets_UserId_CreatedAtUtc");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("DietAI.Api.Services.AiPlanSender.Models.KeycloakUsers", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("KeycloakUsers");

                    b.HasData(
                        new
                        {
                            UniqueId = "019eea6e-aef4-7546-88e2-c4acdbc71872",
                            Email = "test@test.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
